---
- name: Configure profile
  hosts: all
  become: false
  tasks:
    - name: Use alt key as modifier
      ansible.builtin.lineinfile:
        search_string: "set $mod Mod4"
        path: ~/.i3/config
        line: "set $mod Mod1"
      notify: reload i3

    - name: Download wallpaper
      ansible.builtin.get_url:
        url: https://images.pexels.com/photos/2835436/pexels-photo-2835436.jpeg?cs=srgb&dl=pexels-francesco-ungaro-2835436.jpg&fm=jpg   # noqa line-length
        dest: ~/Pictures/wallpaper.jpg
        mode: '0744'
        owner: phillip
        group: phillip
      register: wallpaper

    - name: Disable nitrogen in favor of feh
      ansible.builtin.replace:
        path: ~/.i3/config
        regexp: ^(exec)(.*)(nitrogen)(.*)$
        replace: '# \1\2\3\4'
      
    - name: Configure wallpaper
      ansible.builtin.lineinfile:
        path: ~/.i3/config
        firstmatch: true
        insertafter: '# Autostart applications'
        line: exec --no-startup-id feh --bg-scale /home/phillip/Pictures/wallpaper.jpg
        search_string: feh --bg-scale
        state: present
      notify: restart i3

    - name: load udiskie
      ansible.builtin.lineinfile:
        path: ~/.i3/config
        insertafter: '# Autostart applications'
        line: exec --no-startup-id udiskie
        state: present
        search_string: udiskie
      notify: restart i3

    - name: Enable fake transparency in terminal
      ansible.builtin.lineinfile:
        path: ~/.Xresources
        line: '{{ item.line }}'
        regexp: '{{ item.regex }}'
        state: present
        backup: true
      notify: xrdb reload
      loop:
        - {regex: "(! )?URxvt\\*inheritPixmap:.*", line: "URxvt*inheritPixmap:            true"}
        - {regex: "(! )?URxvt\\*transparent:.*", line: "URxvt*transparent:              true"}
        - {regex: "(! )?URxvt\\*shading:.*", line: "URxvt*shading:                  24"}

    - name: Create i3status dir
      ansible.builtin.file:
        state: directory
        path: ~/.config/i3status
        owner: phillip
        group: phillip
        mode: '0744'

    - name: Configure i3status files
      ansible.builtin.copy:
        src: i3status.conf
        dest: ~/.config/i3status/config
        owner: phillip
        group: phillip
        mode: '0744'
      notify: restart i3

    - name: Create bash alias file
      ansible.builtin.lineinfile:
        path: ~/.bash_alias
        line: "{{ item }}"
        create: true
        owner: phillip
        group: phillip
        mode: '0744'
      loop:
        - "alias ll='ls -alh --color=auto'"
        - "alias gst='git status'"
        - "alias gcmsg='git commit -m '"
        - "alias gaa='git add --all'"

    - name: Link alias file
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        insertafter: EOF
        line: "source $HOME/.bash_alias"

  handlers:
    - name: reload i3
      ansible.builtin.command:
        cmd: i3-msg reload

    - name: restart i3
      ansible.builtin.command:
        cmd: i3-msg restart

    - name: xrdb reload
      ansible.builtin.command:
        cmd: xrdb ~/.Xresources
