---
roles: 
  - name: robertdebock.common
  - name: robertdebock.docker
  - name: robertdebock.docker_compose
  - name: robertdebock.git
  - name: robertdebock.openssh
  - name: robertdebock.virtualbox
  - name: robertdebock.users
collections:
  - name: kewlfft.aur
