---
- name: Configure personal desktop computer
  hosts: all
  become: true
  become_user: root
  roles:
    - kewlfft.aur
  tasks:
    - name: Upgrade system
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install tools
      community.general.pacman:
        state: latest
        name: [firefox, feh, htop, nmon, vim, udisks2, udiskie]

    - name: Install ansible tools (pacman)
      community.general.pacman:
        state: latest
        name: [python3, ansible, ansible-lint, flake8, yamllint]

    - name: Install ansible tools (pip)
      ansible.builtin.pip:
        name: [pytest, pytest-testinfra, molecule, 'molecule[ansible,docker,lint]']

    - name: Disable quiet boot
      ansible.builtin.replace:
        backup: true
        path: /etc/default/grub
        regexp: '(GRUB_CMDLINE_LINUX_DEFAULT=")(.*)(quiet)(.*)(")'
        replace: '\1\2\4\5'
      notify: update grub

    - name: Enable radeon overclocking features
      ansible.builtin.replace:
        backup: true
        path: /etc/default/grub
        regexp: '(GRUB_CMDLINE_LINUX_DEFAULT=")(?!.*? amdgpu.ppfeaturemask=0xffffffff)(.*)(")'
        replace: '\1\2 amdgpu.ppfeaturemask=0xffffffff\3'
      notify: upgrade grub

    - name: Copy low power profile
      ansible.builtin.copy:
        src: 30-radeon-pm.rules
        dest: /etc/udev/rules.d/30-radeon-pm.rules
        owner: root
        group: root
        mode: '0755'
    - name: Common
      ansible.builtin.include_role:
        name: robertdebock.common
      vars:
        _common_requirements:
          Archlinux:
            - net-tools
          default:
            - net-tools

    - name: OpenSSH
      ansible.builtin.include_role:
        name: robertdebock.openssh
      vars:
        _openssh_packages:
          Archlinux:
            - openssh
          default:
            - openssh
        _openssh_template_src:
          Archlinux: sshd_config_Archlinux.j2


    - name: Virtualbox
      ansible.builtin.include_role:
        name: robertdebock.virtualbox
      vars:
        _virtualbox_requirements:
          Archlinux:
            - base-devel
        _virtualbox_package:
          Archlinux: virtualbox

    - name: Include roles
      ansible.builtin.include_role:
        name: "{{ role_name }}"
      loop:
        - robertdebock.docker
        - robertdebock.docker_compose
        - robertdebock.git
        - robertdebock.users
      loop_control:
        loop_var: role_name

    - name: Install autofs
      aur:
        name: "{{ item }}"
        state: present
      become: true
      become_user: aur_builder
      loop:
        - autofs
        - downgrade

    - name: Get systemd version   # noqa command-instead-of-module
      ansible.builtin.command:
        cmd: 'systemctl --version'
      register: systemd
      changed_when: false

    - name: Downgrade systemd
      ansible.builtin.shell:
        cmd: 'yes | DOWNGRADE_FROM_ALA=1 downgrade "{{ item }}==247.4-1" --ala-only'
      when: "'248' in systemd.stdout"
      loop:
        - systemd
        - systemd-libs
        - systemd-resolvconf
        - systemd-sysvcompat

    - name: Ignore systemd updates
      community.general.ini_file:
        create: false
        path: /etc/pacman.conf
        option: IgnorePkg
        section: options
        value: systemd systemd-libs systemd-resolvconf systemd-sysvcompat

  handlers:
    - name: update grub
      ansible.builtin.command:
        cmd: update-grub
